// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SU26_PRN232_Payment.Entities.KhoiDN.Models;

public partial class InvoicesKhoiDn
{
    public int InvoiceKhoiDnid { get; set; }

    public string InvoiceCode { get; set; }

    public int? ParkingSessionId { get; set; }

    public int? UserId { get; set; }

    public decimal BaseFee { get; set; }

    public decimal? PenaltyFee { get; set; }

    public decimal TotalAmount { get; set; }

    public string Status { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public string Description { get; set; }

    public virtual ICollection<TransactionsKhoiDn> TransactionsKhoiDns { get; set; } = new List<TransactionsKhoiDn>();
}