// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SU26_PRN232_Payment.Entities.KhoiDN.Models;

public partial class TransactionsKhoiDn
{
    public int TransactionKhoiDnid { get; set; }

    public string TransactionCode { get; set; }

    public int InvoiceKhoiDnid { get; set; }

    public int? StaffId { get; set; }

    public decimal Amount { get; set; }

    public string PaymentMethod { get; set; }

    public string PaymentStatus { get; set; }

    public string ReferenceCode { get; set; }

    public DateTime? TransactionTime { get; set; }

    public virtual InvoicesKhoiDn InvoiceKhoiDn { get; set; }
}