// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using SU26_PRN232_Payment.Entities.KhoiDN.Models;
using System;
using System.Collections.Generic;

namespace SU26_PRN232_Payment.Repositories.KhoiDN;

public partial class SmartParking_PaymentServiceContext : DbContext
{
    public SmartParking_PaymentServiceContext()
    {
    }

    public SmartParking_PaymentServiceContext(DbContextOptions<SmartParking_PaymentServiceContext> options)
        : base(options)
    {
    }

    public virtual DbSet<InvoicesKhoiDn> InvoicesKhoiDns { get; set; }

    public virtual DbSet<SystemUserAccount> SystemUserAccounts { get; set; }

    public virtual DbSet<TransactionsKhoiDn> TransactionsKhoiDns { get; set; }

    public static string GetConnectionString(string connectionStringName)
    {
        var config = new ConfigurationBuilder()
            .SetBasePath(AppDomain.CurrentDomain.BaseDirectory)
            .AddJsonFile("appsettings.json")
            .Build();

        string connectionString = config.GetConnectionString(connectionStringName);
        return connectionString;
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<InvoicesKhoiDn>(entity =>
        {
            entity.HasKey(e => e.InvoiceKhoiDnid).HasName("PK__Invoices__B222F48BFFD84B76");

            entity.ToTable("InvoicesKhoiDN");

            entity.HasIndex(e => e.InvoiceCode, "UQ__Invoices__0D9D7FF364FEB94C").IsUnique();

            entity.Property(e => e.InvoiceKhoiDnid).HasColumnName("InvoiceKhoiDNId");
            entity.Property(e => e.BaseFee).HasColumnType("decimal(12, 2)");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.InvoiceCode)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.PenaltyFee)
                .HasDefaultValue(0.00m)
                .HasColumnType("decimal(12, 2)");
            entity.Property(e => e.Status)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("UNPAID");
            entity.Property(e => e.TotalAmount).HasColumnType("decimal(12, 2)");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
        });

        modelBuilder.Entity<SystemUserAccount>(entity =>
        {
            entity.HasKey(e => e.UserAccountId);

            entity.ToTable("System.UserAccount");

            entity.Property(e => e.UserAccountId).HasColumnName("UserAccountID");
            entity.Property(e => e.ApplicationCode).HasMaxLength(50);
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.EmployeeCode)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.ModifiedBy).HasMaxLength(50);
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Phone)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.RequestCode).HasMaxLength(50);
            entity.Property(e => e.UserName)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<TransactionsKhoiDn>(entity =>
        {
            entity.HasKey(e => e.TransactionKhoiDnid).HasName("PK__Transact__22AAA98CB9AE27E4");

            entity.ToTable("TransactionsKhoiDN");

            entity.HasIndex(e => e.TransactionCode, "UQ__Transact__D85E702608426CA8").IsUnique();

            entity.Property(e => e.TransactionKhoiDnid).HasColumnName("TransactionKhoiDNId");
            entity.Property(e => e.Amount).HasColumnType("decimal(12, 2)");
            entity.Property(e => e.InvoiceKhoiDnid).HasColumnName("InvoiceKhoiDNId");
            entity.Property(e => e.PaymentMethod)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false);
            entity.Property(e => e.PaymentStatus)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("PENDING");
            entity.Property(e => e.ReferenceCode)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.TransactionCode)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.TransactionTime)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.InvoiceKhoiDn).WithMany(p => p.TransactionsKhoiDns)
                .HasForeignKey(d => d.InvoiceKhoiDnid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FKTransactionsKhoiDNInvoicesKhoiDN");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}